# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DataSourceAdapter.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import Commons_pb2 as Commons__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='DataSourceAdapter.proto',
  package='eu.ifak.ehs',
  syntax='proto3',
  serialized_options=b'P\001',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x17\x44\x61taSourceAdapter.proto\x12\x0b\x65u.ifak.ehs\x1a\rCommons.proto\"\x1e\n\x0bReadRequest\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t\"V\n\x0cReadResponse\x12!\n\x05value\x18\x01 \x01(\x0b\x32\x12.eu.ifak.ehs.Value\x12#\n\x06status\x18\x02 \x01(\x0e\x32\x13.eu.ifak.ehs.Status\"B\n\x0cWriteRequest\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t\x12!\n\x05value\x18\x02 \x01(\x0b\x32\x12.eu.ifak.ehs.Value\"4\n\rWriteResponse\x12#\n\x06status\x18\x02 \x01(\x0e\x32\x13.eu.ifak.ehs.Status2\xb7\x02\n\x11\x44\x61taSourceAdapter\x12=\n\x04ping\x12\x18.eu.ifak.ehs.PingRequest\x1a\x19.eu.ifak.ehs.PingResponse\"\x00\x12=\n\x04read\x12\x18.eu.ifak.ehs.ReadRequest\x1a\x19.eu.ifak.ehs.ReadResponse\"\x00\x12@\n\x05write\x12\x19.eu.ifak.ehs.WriteRequest\x1a\x1a.eu.ifak.ehs.WriteResponse\"\x00\x12\x62\n\x11get_configuration\x12$.eu.ifak.ehs.GetConfigurationRequest\x1a%.eu.ifak.ehs.GetConfigurationResponse\"\x00\x42\x02P\x01\x62\x06proto3'
  ,
  dependencies=[Commons__pb2.DESCRIPTOR,])




_READREQUEST = _descriptor.Descriptor(
  name='ReadRequest',
  full_name='eu.ifak.ehs.ReadRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='address', full_name='eu.ifak.ehs.ReadRequest.address', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=55,
  serialized_end=85,
)


_READRESPONSE = _descriptor.Descriptor(
  name='ReadResponse',
  full_name='eu.ifak.ehs.ReadResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='eu.ifak.ehs.ReadResponse.value', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='status', full_name='eu.ifak.ehs.ReadResponse.status', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=87,
  serialized_end=173,
)


_WRITEREQUEST = _descriptor.Descriptor(
  name='WriteRequest',
  full_name='eu.ifak.ehs.WriteRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='address', full_name='eu.ifak.ehs.WriteRequest.address', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='eu.ifak.ehs.WriteRequest.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=175,
  serialized_end=241,
)


_WRITERESPONSE = _descriptor.Descriptor(
  name='WriteResponse',
  full_name='eu.ifak.ehs.WriteResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='eu.ifak.ehs.WriteResponse.status', index=0,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=243,
  serialized_end=295,
)

_READRESPONSE.fields_by_name['value'].message_type = Commons__pb2._VALUE
_READRESPONSE.fields_by_name['status'].enum_type = Commons__pb2._STATUS
_WRITEREQUEST.fields_by_name['value'].message_type = Commons__pb2._VALUE
_WRITERESPONSE.fields_by_name['status'].enum_type = Commons__pb2._STATUS
DESCRIPTOR.message_types_by_name['ReadRequest'] = _READREQUEST
DESCRIPTOR.message_types_by_name['ReadResponse'] = _READRESPONSE
DESCRIPTOR.message_types_by_name['WriteRequest'] = _WRITEREQUEST
DESCRIPTOR.message_types_by_name['WriteResponse'] = _WRITERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ReadRequest = _reflection.GeneratedProtocolMessageType('ReadRequest', (_message.Message,), {
  'DESCRIPTOR' : _READREQUEST,
  '__module__' : 'DataSourceAdapter_pb2'
  # @@protoc_insertion_point(class_scope:eu.ifak.ehs.ReadRequest)
  })
_sym_db.RegisterMessage(ReadRequest)

ReadResponse = _reflection.GeneratedProtocolMessageType('ReadResponse', (_message.Message,), {
  'DESCRIPTOR' : _READRESPONSE,
  '__module__' : 'DataSourceAdapter_pb2'
  # @@protoc_insertion_point(class_scope:eu.ifak.ehs.ReadResponse)
  })
_sym_db.RegisterMessage(ReadResponse)

WriteRequest = _reflection.GeneratedProtocolMessageType('WriteRequest', (_message.Message,), {
  'DESCRIPTOR' : _WRITEREQUEST,
  '__module__' : 'DataSourceAdapter_pb2'
  # @@protoc_insertion_point(class_scope:eu.ifak.ehs.WriteRequest)
  })
_sym_db.RegisterMessage(WriteRequest)

WriteResponse = _reflection.GeneratedProtocolMessageType('WriteResponse', (_message.Message,), {
  'DESCRIPTOR' : _WRITERESPONSE,
  '__module__' : 'DataSourceAdapter_pb2'
  # @@protoc_insertion_point(class_scope:eu.ifak.ehs.WriteResponse)
  })
_sym_db.RegisterMessage(WriteResponse)


DESCRIPTOR._options = None

_DATASOURCEADAPTER = _descriptor.ServiceDescriptor(
  name='DataSourceAdapter',
  full_name='eu.ifak.ehs.DataSourceAdapter',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=298,
  serialized_end=609,
  methods=[
  _descriptor.MethodDescriptor(
    name='ping',
    full_name='eu.ifak.ehs.DataSourceAdapter.ping',
    index=0,
    containing_service=None,
    input_type=Commons__pb2._PINGREQUEST,
    output_type=Commons__pb2._PINGRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='read',
    full_name='eu.ifak.ehs.DataSourceAdapter.read',
    index=1,
    containing_service=None,
    input_type=_READREQUEST,
    output_type=_READRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='write',
    full_name='eu.ifak.ehs.DataSourceAdapter.write',
    index=2,
    containing_service=None,
    input_type=_WRITEREQUEST,
    output_type=_WRITERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='get_configuration',
    full_name='eu.ifak.ehs.DataSourceAdapter.get_configuration',
    index=3,
    containing_service=None,
    input_type=Commons__pb2._GETCONFIGURATIONREQUEST,
    output_type=Commons__pb2._GETCONFIGURATIONRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_DATASOURCEADAPTER)

DESCRIPTOR.services_by_name['DataSourceAdapter'] = _DATASOURCEADAPTER

# @@protoc_insertion_point(module_scope)
